name: lesson
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  path: ^1.8.0
  date_format: ^2.0.7
  rxdart: ^0.27.7
  equatable: ^2.0.5
  meta: ^1.9.0
  enum_assist_annotation: any
  analyzer: ^2.5.0


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_runner: any
  enum_assist: any
